# Generated by Django 3.2 on 2022-06-22 03:46

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellido', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=100)),
                ('cliente_direccion', models.CharField(max_length=100)),
                ('cliente_pais', models.CharField(max_length=100)),
                ('cliente_ciudad', models.CharField(max_length=100)),
                ('cliente_fecha_nacimiento', models.DateField()),
                ('cliente_foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('compra_fecha', models.DateField()),
                ('compra_hora', models.TimeField()),
                ('estado', models.CharField(default='Solicitado', max_length=20)),
                ('compra_nro', models.CharField(default='', max_length=100, verbose_name='Nro Pedido')),
                ('compratour_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Compra', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_nombre', models.CharField(max_length=100)),
                ('tour_descripcion', models.TextField()),
                ('tour_itinerario1', models.TextField()),
                ('tour_itinerario2', models.TextField(blank=True, null=True)),
                ('tour_itinerario3', models.TextField(blank=True, null=True)),
                ('tour_itinerario4', models.TextField(blank=True, null=True)),
                ('tour_itinerario5', models.TextField(blank=True, null=True)),
                ('tour_recomendaciones', models.TextField(blank=True, null=True)),
                ('tour_restaurante', models.TextField(blank=True, null=True)),
                ('tour_atractivos', models.TextField(blank=True, null=True)),
                ('tour_precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('tour_precio_oferta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio')),
                ('tour_foto1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('tour_foto2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('tour_foto3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('tour_foto4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('tour_foto5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('tour_stock', models.IntegerField(default=0)),
                ('tour_fecha_inicio', models.DateField()),
                ('tour_fecha_fin', models.DateField()),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Tour', to='tour.region', verbose_name='region')),
            ],
        ),
        migrations.CreateModel(
            name='CompraTour',
            fields=[
                ('compratour_id', models.AutoField(primary_key=True, serialize=False)),
                ('compratour_cantidad', models.IntegerField(default=1)),
                ('tour_precio_oferta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra_id', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.RESTRICT, related_name='compratours', to='tour.compra', verbose_name='Compra')),
                ('tour_id', models.ForeignKey(db_column='tour_id', on_delete=django.db.models.deletion.RESTRICT, related_name='compratours', to='tour.tour', verbose_name='Tour')),
            ],
        ),
    ]
