# Generated by Django 3.2 on 2022-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cliente_fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
