# Generated by Django 3.2 on 2022-06-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_myuser_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_include',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_noincluye',
            field=models.TextField(blank=True, null=True),
        ),
    ]
