# Generated by Django 3.2 on 2022-06-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20220621_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_include',
            new_name='tour_incluye',
        ),
    ]
