# Generated by Django 3.2 on 2022-06-22 04:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_rename_tour_include_tour_tour_incluye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_foto1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_foto2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_foto3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_foto4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_foto5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_precio_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
