# Generated by Django 3.2 on 2022-06-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20220621_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
